version: '3'

services:
  rstudio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: targets-rstudio
    environment:
      DISABLE_AUTH: true
      ROOT: true
    ports:
      - 8787:8787
    links: 
      - minio
    volumes:
      - ./code:/home/rstudio/code

  minio:
      # image: docker.io/bitnami/minio:2022
      image: minio/minio:RELEASE.2024-04-06T05-26-02Z
      container_name: targets-minio
      restart: unless-stopped
      ports:
        - 9008:9000 # 9000 internal docker network
        - 9009:9001 # UI 9091 external access
      environment:
        MINIO_ROOT_USER: minio
        MINIO_ROOT_PASSWORD: minio123
        TZ: UTC
      volumes:
        - ./minio/data:/data
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
        interval: 30s
        timeout: 20s
        retries: 3
      command: minio server /data --console-address ":9001"

  createRbuckets:
      image: minio/mc
      container_name: targets-createRbuckets
      depends_on:
        - minio
      entrypoint: >
        /bin/sh -c "
        /usr/bin/mc alias set myminio http://minio:9000 minio minio123;
        /usr/bin/mc mb myminio/targets-versioned;
        /usr/bin/mc version enable myminio/targets-versioned;
        /usr/bin/mc anonymous set public myminio/targets-versioned;
        exit 0;
        "    
  